apiVersion: v1
kind: Service
metadata:
  name: front-svc
  labels:
    app: front-svc
spec:
  selector:
    app: front-svc
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: NodePort
